### ISSUE TITLE
Website: Wrong padding for titles.

### ISSUE THREAD

**Issue by y0nd0** [love2d/love#1702]
This is about the [website](https://love2d.org/).

![image](https://user-images.githubusercontent.com/68586847/118361233-ba430200-b58a-11eb-8bde-fb3e3279ec9c.png)

You can see that the padding of both titles are wrong. It should be flipped. The left one should have 80px and the right one 45px (which is the default padding I see in the DevTools).

Here is the fix. Search the css file for that selectors and set 45px <-> 80px.

```css
section#features > section#opensource > h2 {
  padding-left: 45px;
}

section#features > section#community > h2 {
  padding-left: 80px;
}
```

and ... voila:

![image](https://user-images.githubusercontent.com/68586847/118361348-5836cc80-b58b-11eb-8024-9961499e4728.png)
